/* Banque de questions Regafy — 51 questions bilingues, groupées par FAMILLE.
   Tirage (quiz.js) : 10 familles au hasard, 1 question au hasard par famille —
   deux variantes d'une même question ne tombent jamais dans la même partie.
   Variantes : reformulations, négations, réponses déplacées. Familles q01–q10 =
   questions validées CEO 2026-07-17 ; le reste = extensions à faire relire.
   ⚠️ COPIE GÉNÉRÉE depuis public/bank.js (préfixe export) — modifier public/bank.js puis recopier. */

'use strict';

export const BANK = [
  /* ── F1 · États membres ── */
  { id: 'q01a', family: 'membres', answer: 1,
    fr: { domain: 'Institutions', text: "Combien d'États membres compte l'espace UEMOA ?", options: ['6', '8', '12', '15'], explain: "Huit : Bénin, Burkina Faso, Côte d'Ivoire, Guinée-Bissau, Mali, Niger, Sénégal et Togo — un marché pharmaceutique qui partage le franc CFA et un cadre d'harmonisation commun.", source: "Traité de l'UEMOA" },
    en: { domain: 'Institutions', text: 'How many member states make up the WAEMU (UEMOA) area?', options: ['6', '8', '12', '15'], explain: "Eight: Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal and Togo — a pharmaceutical market sharing the CFA franc and a common harmonisation framework.", source: 'WAEMU Treaty' } },
  { id: 'q01b', family: 'membres', answer: 2,
    fr: { domain: 'Institutions', text: "Lequel de ces pays n'est PAS membre de l'UEMOA ?", options: ['Le Togo', 'Le Mali', 'Le Ghana', 'Le Bénin'], explain: "Le Ghana est membre de la CEDEAO mais pas de l'UEMOA — l'union monétaire compte 8 États, tous francophones ou lusophone (Guinée-Bissau).", source: "Traité de l'UEMOA" },
    en: { domain: 'Institutions', text: 'Which of these countries is NOT a WAEMU member?', options: ['Togo', 'Mali', 'Ghana', 'Benin'], explain: 'Ghana belongs to ECOWAS but not to WAEMU — the monetary union counts 8 states.', source: 'WAEMU Treaty' } },
  { id: 'q01c', family: 'membres', answer: 0,
    fr: { domain: 'Institutions', text: 'Quelle monnaie partagent les États membres de l’UEMOA ?', options: ['Le franc CFA', "L'éco", 'Le naira', 'Chaque État a sa monnaie'], explain: "Le franc CFA (XOF) est la monnaie commune des 8 États — un atout pratique pour budgétiser les redevances réglementaires de la zone.", source: "Traité de l'UEMOA" },
    en: { domain: 'Institutions', text: 'Which currency do WAEMU member states share?', options: ['The CFA franc', 'The eco', 'The naira', 'Each state has its own'], explain: 'The CFA franc (XOF) is the common currency of the 8 states — convenient when budgeting regulatory fees across the area.', source: 'WAEMU Treaty' } },

  /* ── F2 · Langue de soumission ── */
  { id: 'q02a', family: 'langue', answer: 1,
    fr: { domain: 'Langue de soumission', text: "Dans une soumission aux autorités de l'espace UEMOA, quels documents doivent impérativement être en français ?", options: ['Uniquement le RCP et la notice patient', 'La correspondance officielle, le RCP, la notice patient et les emballages primaires & secondaires', "Uniquement la correspondance officielle avec l'autorité", "Aucun — l'anglais est accepté pour tout le dossier"], explain: "Le français s'impose partout où l'autorité et le patient lisent : correspondance officielle, RCP, notice patient et articles de conditionnement. Les parties techniques du dossier (modules qualité du CTD) sont plus souvent tolérées en anglais.", source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Submission language', text: 'In a submission to a WAEMU-area authority, which documents must be in French?', options: ['Only the SmPC and the patient leaflet', 'Official correspondence, the SmPC, the patient leaflet, and primary & secondary packaging', 'Only the official correspondence with the authority', 'None — English is accepted for the whole dossier'], explain: 'French is required wherever the authority and the patient read: official correspondence, SmPC, patient leaflet and packaging components. The technical parts (CTD quality modules) are more often accepted in English.', source: 'Practice of WAEMU-area authorities' } },
  { id: 'q02b', family: 'langue', answer: 2,
    fr: { domain: 'Langue de soumission', text: 'Les modules techniques (qualité) du CTD doivent-ils obligatoirement être rédigés en français ?', options: ['Oui, comme tout le dossier', "Oui, sauf dérogation écrite", "Non — ils sont souvent acceptés en anglais, contrairement au RCP, à la notice et aux emballages", 'Non — ils peuvent être dans n’importe quelle langue'], explain: "Les autorités tolèrent le plus souvent l'anglais pour les modules techniques ; en revanche RCP, notice patient, emballages et correspondance officielle restent en français.", source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Submission language', text: 'Must the technical (quality) modules of the CTD be written in French?', options: ['Yes, like the whole dossier', 'Yes, unless a written waiver is granted', 'No — they are often accepted in English, unlike the SmPC, leaflet and packaging', 'No — any language is fine'], explain: 'Authorities most often accept English for the technical modules; the SmPC, patient leaflet, packaging and official correspondence remain in French.', source: 'Practice of WAEMU-area authorities' } },
  { id: 'q02c', family: 'langue', answer: 0,
    fr: { domain: 'Langue de soumission', text: "Dans quelle langue la notice patient doit-elle être rédigée pour l'espace UEMOA ?", options: ['En français', 'En anglais', 'Au choix du laboratoire', 'Dans la langue du pays de fabrication'], explain: 'La notice s’adresse au patient : elle doit être lisible par lui — donc en français dans l’espace UEMOA.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Submission language', text: 'In which language must the patient leaflet be written for the WAEMU area?', options: ['In French', 'In English', "At the company's discretion", 'In the language of the manufacturing country'], explain: 'The leaflet is for the patient: it must be readable by them — hence French in the WAEMU area.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F3 · Règlement d'harmonisation ── */
  { id: 'q03a', family: 'reglement', answer: 1,
    fr: { domain: 'Harmonisation régionale', text: "Quel texte régional harmonise les procédures d'homologation des produits pharmaceutiques à usage humain dans les États membres de l'UEMOA ?", options: ['La directive n° 03/2006/CM/UEMOA', 'Le règlement n° 06/2010/CM/UEMOA', "La décision n° 09/2015 de l'OOAS", 'Le protocole de Ouagadougou'], explain: "Le règlement n° 06/2010/CM/UEMOA pose le socle commun des procédures d'homologation dans les huit États membres.", source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Regional harmonisation', text: 'Which regional text harmonises marketing-authorisation procedures for human medicines across WAEMU member states?', options: ['Directive No. 03/2006/CM/UEMOA', 'Regulation No. 06/2010/CM/UEMOA', 'WAHO Decision No. 09/2015', 'The Ouagadougou Protocol'], explain: 'Regulation No. 06/2010/CM/UEMOA lays the common foundation for authorisation procedures across the eight member states.', source: 'Regulation No. 06/2010/CM/UEMOA' } },
  { id: 'q03b', family: 'reglement', answer: 3,
    fr: { domain: 'Harmonisation régionale', text: 'Le règlement n° 06/2010/CM/UEMOA porte sur…', options: ['La fiscalité des laboratoires', 'La libre circulation des pharmaciens', 'Les essais cliniques uniquement', "L'harmonisation des procédures d'homologation des médicaments à usage humain"], explain: "C'est LE texte de référence de l'harmonisation réglementaire pharmaceutique dans l'union — à citer dans vos argumentaires régionaux.", source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Regional harmonisation', text: 'Regulation No. 06/2010/CM/UEMOA deals with…', options: ['Corporate taxation of pharma companies', 'Free movement of pharmacists', 'Clinical trials only', 'Harmonisation of authorisation procedures for human medicines'], explain: 'It is THE reference text for pharmaceutical regulatory harmonisation in the union.', source: 'Regulation No. 06/2010/CM/UEMOA' } },

  /* ── F4 · CTD ── */
  { id: 'q04a', family: 'ctd', answer: 1,
    fr: { domain: "Dossier d'AMM", text: "Sous quel format les dossiers de demande d'AMM sont-ils attendus dans l'espace UEMOA ?", options: ['Format libre, selon le laboratoire', 'Format CTD (Common Technical Document)', 'eCTD exclusivement, en soumission électronique', 'Format ACTD (ASEAN)'], explain: "Le CTD structure le dossier en 5 modules. L'eCTD n'est pas encore une exigence généralisée dans la région.", source: "Lignes directrices d'homologation UEMOA" },
    en: { domain: 'MA dossier', text: 'In which format are marketing-authorisation dossiers expected in the WAEMU area?', options: ['Free format', 'CTD format (Common Technical Document)', 'eCTD only, electronic submission', 'ACTD format (ASEAN)'], explain: 'The CTD structures the dossier into 5 modules. eCTD is not yet a general requirement in the region.', source: 'WAEMU authorisation guidelines' } },
  { id: 'q04b', family: 'ctd', answer: 2,
    fr: { domain: "Dossier d'AMM", text: 'Combien de modules composent un dossier au format CTD ?', options: ['3', '4', '5', '7'], explain: 'Cinq : module 1 (administratif régional), 2 (résumés), 3 (qualité), 4 (non-clinique), 5 (clinique).', source: 'Format CTD (ICH)' },
    en: { domain: 'MA dossier', text: 'How many modules make up a CTD dossier?', options: ['3', '4', '5', '7'], explain: 'Five: module 1 (regional administrative), 2 (summaries), 3 (quality), 4 (non-clinical), 5 (clinical).', source: 'CTD format (ICH)' } },
  { id: 'q04c', family: 'ctd', answer: 0,
    fr: { domain: "Dossier d'AMM", text: 'Dans le CTD, quel module contient les informations administratives régionales (formulaires, RCP, étiquetage) ?', options: ['Le module 1', 'Le module 2', 'Le module 3', 'Le module 5'], explain: "Le module 1 est le seul non harmonisé par l'ICH : chaque région y met ses exigences administratives — c'est lui qui varie d'un pays UEMOA à l'autre.", source: 'Format CTD (ICH)' },
    en: { domain: 'MA dossier', text: 'In the CTD, which module contains the regional administrative information (forms, SmPC, labelling)?', options: ['Module 1', 'Module 2', 'Module 3', 'Module 5'], explain: 'Module 1 is the only one not harmonised by ICH: each region puts its administrative requirements there — the module that changes from one WAEMU country to another.', source: 'CTD format (ICH)' } },

  /* ── F5 · Durée de vie des échantillons ── */
  { id: 'q05a', family: 'echantillons', answer: 2,
    fr: { domain: 'Échantillons', text: 'Quelle durée de vie restante est exigée pour les échantillons soumis avec le dossier ?', options: ['6 mois minimum', '12 mois minimum', 'Au moins 18 mois, ou les 2/3 de la durée de conservation', 'Aucune exigence particulière'], explain: 'À la soumission, les échantillons doivent conserver au moins 18 mois de validité — ou les deux tiers de leur durée de conservation totale.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Samples', text: 'What remaining shelf life is required for samples submitted with the dossier?', options: ['At least 6 months', 'At least 12 months', 'At least 18 months, or two-thirds of the shelf life', 'No particular requirement'], explain: 'At submission, samples must retain at least 18 months of validity — or two-thirds of their total shelf life.', source: 'Practice of WAEMU-area authorities' } },
  { id: 'q05b', family: 'echantillons', answer: 1,
    fr: { domain: 'Échantillons', text: 'Un échantillon dont il ne reste que 8 mois de validité est-il recevable à l’enregistrement ?', options: ["Oui, tant qu'il n'est pas périmé", 'Non — il faut au moins 18 mois restants, ou les 2/3 de la durée de conservation', 'Oui, avec une lettre d’engagement', 'Oui, si le produit est un générique'], explain: 'Trop entamé : la règle des 18 mois (ou 2/3 de la durée de vie) protège l’autorité, qui évalue un produit encore représentatif.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Samples', text: 'Is a sample with only 8 months of shelf life left acceptable for registration?', options: ['Yes, as long as it has not expired', 'No — at least 18 months remaining, or two-thirds of the shelf life, are required', 'Yes, with a commitment letter', 'Yes, if the product is a generic'], explain: 'Too far gone: the 18-months (or two-thirds) rule ensures the authority assesses a still-representative product.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F6 · AMM ── */
  { id: 'q06a', family: 'amm', answer: 1,
    fr: { domain: 'Fondamentaux', text: "Comment s'appelle le document qui autorise officiellement un laboratoire à vendre son médicament dans un pays de l'UEMOA ?", options: ['Le certificat GMP', "L'AMM — Autorisation de Mise sur le Marché", 'Le CPP', "La licence d'exploitation"], explain: "L'AMM est LE sésame : sans elle, pas de commercialisation légale. GMP et CPP sont des pièces du dossier — pas l'autorisation elle-même.", source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Fundamentals', text: 'What is the document that officially authorises a company to market its medicine in a WAEMU country?', options: ['The GMP certificate', 'The Marketing Authorisation (MA / AMM)', 'The CPP', 'The operating licence'], explain: 'The MA is THE key: without it, no legal marketing. GMP and CPP are supporting documents — not the authorisation itself.', source: 'Regulation No. 06/2010/CM/UEMOA' } },
  { id: 'q06b', family: 'amm', answer: 3,
    fr: { domain: 'Fondamentaux', text: 'Que signifie le sigle AMM ?', options: ['Accord de Mise en Marche', 'Autorisation Médicale Mutualisée', 'Attestation de Marché du Médicament', 'Autorisation de Mise sur le Marché'], explain: "L'Autorisation de Mise sur le Marché — délivrée par l'autorité nationale de réglementation pharmaceutique de chaque État.", source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Fundamentals', text: 'What does « AMM » stand for (the French acronym used across the region)?', options: ['Accord de Mise en Marche', 'Autorisation Médicale Mutualisée', 'Attestation de Marché du Médicament', 'Autorisation de Mise sur le Marché'], explain: 'Autorisation de Mise sur le Marché — the Marketing Authorisation, issued by each state’s national regulatory authority.', source: 'Regulation No. 06/2010/CM/UEMOA' } },
  { id: 'q06c', family: 'amm', answer: 2,
    fr: { domain: 'Fondamentaux', text: 'Un médicament peut-il être commercialisé légalement sans AMM valide ?', options: ['Oui, si le laboratoire est certifié GMP', 'Oui, pendant l’instruction du dossier', 'Non, jamais', 'Oui, pour les génériques'], explain: "Jamais : l'AMM est la condition sine qua non de la commercialisation légale — certification GMP ou statut de générique n'y changent rien.", source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Fundamentals', text: 'Can a medicine be legally marketed without a valid Marketing Authorisation?', options: ['Yes, if the company is GMP-certified', 'Yes, while the dossier is under review', 'No, never', 'Yes, for generics'], explain: 'Never: the MA is the sine qua non of legal marketing — GMP certification or generic status change nothing.', source: 'Regulation No. 06/2010/CM/UEMOA' } },

  /* ── F7 · Renouvellement ── */
  { id: 'q07a', family: 'renouvellement', answer: 2,
    fr: { domain: 'Cycle de vie', text: "Le renouvellement d'une AMM se prépare à partir de combien de temps avant son expiration ?", options: ['1 mois', '3 mois', 'Au moins 6 mois', 'Il est automatique'], explain: "Au moins 6 mois avant l'échéance : redevances, documents à jour, échantillons selon les pays… C'est l'échéance la plus souvent ratée.", source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Lifecycle', text: 'How long before its expiry should the renewal of a Marketing Authorisation be prepared?', options: ['1 month', '3 months', 'At least 6 months', 'Renewal is automatic'], explain: 'At least 6 months before expiry: fees, updated documents, samples depending on the country… The deadline most often missed.', source: 'Practice of WAEMU-area authorities' } },
  { id: 'q07b', family: 'renouvellement', answer: 0,
    fr: { domain: 'Cycle de vie', text: "À 2 mois de l'expiration de votre AMM, êtes-vous dans les temps pour lancer le renouvellement ?", options: ['Non — il fallait s’y prendre au moins 6 mois avant', 'Oui, largement', 'Oui, la loi prévoit 1 mois', "Peu importe, l'AMM ne s'éteint jamais"], explain: 'Trop tard pour être serein : la préparation démarre au moins 6 mois avant l’échéance. À 2 mois, le risque de rupture de couverture réglementaire est réel.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Lifecycle', text: 'Two months before your MA expires — are you still on time to start the renewal?', options: ['No — it should have started at least 6 months before', 'Yes, plenty of time', 'Yes, the law provides for 1 month', "It doesn't matter, an MA never lapses"], explain: 'Too late for comfort: preparation starts at least 6 months before expiry. At 2 months, the risk of a regulatory coverage gap is real.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F8 · Variations ── */
  { id: 'q08a', family: 'variations', answer: 1,
    fr: { domain: 'Variations', text: "Le changement du nom commercial d'un produit relève de quel type de variation ?", options: ['Variation majeure', 'Variation mineure', "Nouvelle demande d'AMM complète", 'Simple information, sans dossier'], explain: "C'est une variation mineure — mais une variation quand même : elle se déclare et se documente auprès de l'autorité.", source: 'Lignes directrices variations, espace UEMOA' },
    en: { domain: 'Variations', text: "A change of a product's trade name falls under which type of variation?", options: ['Major variation', 'Minor variation', 'A complete new MA application', 'Simple information, no dossier'], explain: 'A minor variation — but a variation nonetheless: it must be declared and documented with the authority.', source: 'Variation guidelines, WAEMU area' } },
  { id: 'q08b', family: 'variations', answer: 3,
    fr: { domain: 'Variations', text: "Une extension d'indication thérapeutique relève plutôt de…", options: ['Une simple notification', "Aucune démarche si le dosage est inchangé", 'Une variation mineure', 'Une variation majeure'], explain: "Modifier ce que soigne le produit touche au rapport bénéfice/risque : c'est une variation majeure, avec données cliniques à l'appui.", source: 'Lignes directrices variations, espace UEMOA' },
    en: { domain: 'Variations', text: 'An extension of therapeutic indication is rather…', options: ['A simple notification', 'No action needed if the strength is unchanged', 'A minor variation', 'A major variation'], explain: 'Changing what the product treats touches the benefit/risk balance: a major variation, supported by clinical data.', source: 'Variation guidelines, WAEMU area' } },
  { id: 'q08c', family: 'variations', answer: 1,
    fr: { domain: 'Variations', text: "Peut-on modifier le RCP d'un produit enregistré sans en informer l'autorité ?", options: ['Oui, le RCP appartient au laboratoire', 'Non — toute modification passe par une variation déclarée', 'Oui, pour les corrections de forme', "Oui, si le changement vient de l'OMS"], explain: 'Le RCP enregistré fait partie de l’AMM : toute modification, même éditoriale, passe par le circuit des variations.', source: 'Lignes directrices variations, espace UEMOA' },
    en: { domain: 'Variations', text: 'Can you modify the SmPC of a registered product without informing the authority?', options: ['Yes, the SmPC belongs to the company', 'No — any change goes through a declared variation', 'Yes, for editorial fixes', 'Yes, if the change comes from WHO'], explain: 'The registered SmPC is part of the MA: any change, even editorial, goes through the variation process.', source: 'Variation guidelines, WAEMU area' } },

  /* ── F9 · Pièces administratives ── */
  { id: 'q09a', family: 'pieces', answer: 1,
    fr: { domain: "Dossier d'AMM", text: "Quelles pièces administratives sont le plus fréquemment demandées aux laboratoires lors d'une demande d'AMM ?", options: ['Le certificat GMP uniquement', 'Certificat GMP, CPP, certificat de libre vente (FSC) et licence de fabrication', 'Une simple lettre de demande suffit', "Le rapport d'audit interne du laboratoire"], explain: 'Le quatuor classique : GMP (bonnes pratiques de fabrication), CPP (modèle OMS), certificat de libre vente et licence de fabrication.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'MA dossier', text: 'Which administrative documents are most frequently requested from pharmaceutical companies in an MA application?', options: ['The GMP certificate only', 'GMP certificate, CPP, Free Sale Certificate (FSC) and Manufacturing Licence', 'A simple request letter is enough', "The company's internal audit report"], explain: 'The classic quartet: GMP (good manufacturing practice), CPP (WHO scheme), Free Sale Certificate and Manufacturing Licence.', source: 'Practice of WAEMU-area authorities' } },
  { id: 'q09b', family: 'pieces', answer: 0,
    fr: { domain: "Dossier d'AMM", text: 'Que signifie le sigle CPP ?', options: ['Certificat de Produit Pharmaceutique', 'Certificat de Provenance Pharmaceutique', 'Contrôle de Production Pharmaceutique', 'Certificat de Pharmacovigilance Produit'], explain: "Le Certificat de Produit Pharmaceutique, délivré selon le modèle de l'OMS par l'autorité du pays d'origine — pièce quasi systématique du dossier d'AMM.", source: 'Système de certification OMS' },
    en: { domain: 'MA dossier', text: 'What does CPP stand for?', options: ['Certificate of Pharmaceutical Product', 'Certificate of Pharmaceutical Provenance', 'Control of Pharmaceutical Production', 'Certificate of Product Pharmacovigilance'], explain: 'The Certificate of Pharmaceutical Product, issued under the WHO scheme by the authority of the country of origin — a near-systematic piece of the MA dossier.', source: 'WHO certification scheme' } },
  { id: 'q09c', family: 'pieces', answer: 2,
    fr: { domain: "Dossier d'AMM", text: "Qu'atteste le certificat de libre vente (FSC) ?", options: ["Que le produit est exonéré de taxes à l'export", 'Que le prix du produit est libre', "Que le produit est librement commercialisé dans son pays d'origine", 'Que le produit est en vente libre sans ordonnance'], explain: "Le Free Sale Certificate prouve que le produit est réellement commercialisé (ou autorisé) dans son pays d'origine — gage de confiance pour l'autorité de destination.", source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'MA dossier', text: 'What does the Free Sale Certificate (FSC) attest?', options: ['That the product is tax-exempt for export', 'That the product price is unregulated', 'That the product is freely marketed in its country of origin', 'That the product is sold over the counter'], explain: 'The FSC proves the product is genuinely marketed (or authorised) in its country of origin — a trust signal for the destination authority.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F10 · Reconnaissance mutuelle & AMA ── */
  { id: 'q10a', family: 'reconnaissance', answer: 2,
    fr: { domain: 'Harmonisation continentale', text: "L'UEMOA étant un espace économique commun, une AMM obtenue en Côte d'Ivoire permet-elle de vendre légalement au Bénin et au Sénégal sans autorisation supplémentaire ?", options: ["Oui, l'AMM vaut pour les 8 États", 'Oui, après une simple notification', "Non — chaque État délivre sa propre AMM ; mais l'AMA et l'harmonisation régionale y travaillent", "Non, et aucune harmonisation n'est envisagée"], explain: "Chaque autorité nationale délivre sa propre AMM. La bonne nouvelle : règlement UEMOA, OOAS et l'Agence africaine du médicament (AMA) préparent la reconnaissance mutuelle de demain.", source: 'Traité AMA · règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Continental harmonisation', text: "WAEMU being a common economic area, does an MA obtained in Côte d'Ivoire allow you to sell legally in Benin and Senegal without further authorisation?", options: ['Yes, the MA is valid across the 8 states', 'Yes, after a simple notification', 'No — each state issues its own MA; but the AMA and regional harmonisation are working on it', 'No, and no harmonisation is planned'], explain: "Each national authority issues its own MA. The good news: the WAEMU regulation, WAHO and the African Medicines Agency (AMA) are paving the way for mutual recognition.", source: 'AMA Treaty · Regulation No. 06/2010/CM/UEMOA' } },
  { id: 'q10b', family: 'reconnaissance', answer: 1,
    fr: { domain: 'Harmonisation continentale', text: "Que désigne l'AMA ?", options: ["L'Association des Médecins d'Afrique", "L'Agence africaine du médicament, créée par un traité de l'Union africaine", "L'Autorité des Marchés Africains", "L'Alliance des Ministères et Agences"], explain: "L'African Medicines Agency, née d'un traité de l'Union africaine : l'institution continentale appelée à coordonner l'évaluation et la reconnaissance mutuelle.", source: 'Traité AMA (Union africaine)' },
    en: { domain: 'Continental harmonisation', text: 'What is the AMA?', options: ['The African Medical Association', 'The African Medicines Agency, created by an African Union treaty', 'The African Markets Authority', 'The Alliance of Ministries and Agencies'], explain: 'The African Medicines Agency, born of an African Union treaty: the continental institution set to coordinate assessment and mutual recognition.', source: 'AMA Treaty (African Union)' } },

  /* ── F11 · GMP ── */
  { id: 'q11a', family: 'gmp', answer: 1,
    fr: { domain: 'Qualité', text: "Qu'atteste un certificat GMP ?", options: ["La qualité intrinsèque d'un lot précis", 'La conformité du site de fabrication aux bonnes pratiques de fabrication', "L'efficacité clinique du produit", "L'enregistrement du produit dans le pays d'origine"], explain: 'Le certificat GMP (BPF) atteste que le SITE de fabrication opère selon les bonnes pratiques — il parle de l’usine, pas d’un lot ni de l’efficacité.', source: 'Référentiels BPF/GMP (OMS)' },
    en: { domain: 'Quality', text: 'What does a GMP certificate attest?', options: ['The intrinsic quality of a specific batch', 'The manufacturing site’s compliance with good manufacturing practices', "The product's clinical efficacy", "The product's registration in its country of origin"], explain: 'The GMP certificate attests that the manufacturing SITE operates under good practices — it speaks about the plant, not a batch or efficacy.', source: 'GMP references (WHO)' } },
  { id: 'q11b', family: 'gmp', answer: 2,
    fr: { domain: 'Qualité', text: 'Que signifie GMP ?', options: ['General Medical Procedures', 'Global Medicine Protocol', 'Good Manufacturing Practices (bonnes pratiques de fabrication)', 'Guaranteed Medical Product'], explain: 'Good Manufacturing Practices — BPF en français : le référentiel qualité des sites de production pharmaceutique.', source: 'Référentiels BPF/GMP (OMS)' },
    en: { domain: 'Quality', text: 'What does GMP stand for?', options: ['General Medical Procedures', 'Global Medicine Protocol', 'Good Manufacturing Practices', 'Guaranteed Medical Product'], explain: 'Good Manufacturing Practices — the quality reference framework for pharmaceutical production sites.', source: 'GMP references (WHO)' } },

  /* ── F12 · Pharmacovigilance ── */
  { id: 'q12a', family: 'pharmacovigilance', answer: 0,
    fr: { domain: 'Pharmacovigilance', text: 'La pharmacovigilance consiste à…', options: ['Surveiller les effets indésirables des médicaments après leur mise sur le marché', 'Contrôler les prix des médicaments', 'Auditer les usines de fabrication', 'Suivre les ventes des concurrents'], explain: "Une AMM n'est pas la fin de l'histoire : le titulaire doit surveiller et déclarer les effets indésirables tout au long de la vie du produit.", source: 'Bonnes pratiques de pharmacovigilance (OMS)' },
    en: { domain: 'Pharmacovigilance', text: 'Pharmacovigilance consists of…', options: ['Monitoring adverse drug reactions after the product reaches the market', 'Controlling medicine prices', 'Auditing manufacturing plants', "Tracking competitors' sales"], explain: 'An MA is not the end of the story: the holder must monitor and report adverse reactions throughout the product’s life.', source: 'Good pharmacovigilance practices (WHO)' } },
  { id: 'q12b', family: 'pharmacovigilance', answer: 3,
    fr: { domain: 'Pharmacovigilance', text: "Comment s'appelle la surveillance des effets indésirables APRÈS la commercialisation d'un médicament ?", options: ['La bioéquivalence', 'La matériovigilance', "L'hémovigilance", 'La pharmacovigilance'], explain: 'La pharmacovigilance — une obligation du titulaire d’AMM, de plus en plus scrutée par les autorités de la région.', source: 'Bonnes pratiques de pharmacovigilance (OMS)' },
    en: { domain: 'Pharmacovigilance', text: 'What do you call the monitoring of adverse effects AFTER a medicine is marketed?', options: ['Bioequivalence', 'Materiovigilance', 'Haemovigilance', 'Pharmacovigilance'], explain: 'Pharmacovigilance — an MA holder’s obligation, increasingly scrutinised by the region’s authorities.', source: 'Good pharmacovigilance practices (WHO)' } },

  /* ── F13 · Stabilité ── */
  { id: 'q13a', family: 'stabilite', answer: 1,
    fr: { domain: 'Qualité', text: "Quelle zone climatique ICH/OMS s'applique aux études de stabilité destinées à l'Afrique de l'Ouest ?", options: ['Zone II (tempérée méditerranéenne)', 'Zone IVb (chaude et très humide — 30 °C / 75 % HR)', 'Zone I (tempérée)', 'Zone III (chaude et sèche)'], explain: "L'Afrique de l'Ouest relève de la zone IVb : les études de stabilité doivent être conduites à 30 °C / 75 % d'humidité relative.", source: 'Classification climatique ICH/OMS' },
    en: { domain: 'Quality', text: 'Which ICH/WHO climatic zone applies to stability studies intended for West Africa?', options: ['Zone II (Mediterranean temperate)', 'Zone IVb (hot and very humid — 30 °C / 75% RH)', 'Zone I (temperate)', 'Zone III (hot and dry)'], explain: 'West Africa falls under zone IVb: stability studies must be run at 30 °C / 75% relative humidity.', source: 'ICH/WHO climatic classification' } },
  { id: 'q13b', family: 'stabilite', answer: 2,
    fr: { domain: 'Qualité', text: "La date de péremption d'un médicament est déterminée par…", options: ['Le service marketing', 'La date de fabrication plus 5 ans, toujours', 'Les études de stabilité', "La réglementation douanière"], explain: 'Ce sont les études de stabilité (dans la bonne zone climatique !) qui fondent la durée de conservation revendiquée.', source: 'Lignes directrices stabilité (ICH/OMS)' },
    en: { domain: 'Quality', text: "A medicine's expiry date is determined by…", options: ['The marketing department', 'Manufacturing date plus 5 years, always', 'Stability studies', 'Customs regulations'], explain: 'Stability studies (in the right climatic zone!) are what substantiate the claimed shelf life.', source: 'Stability guidelines (ICH/WHO)' } },

  /* ── F14 · OOAS ── */
  { id: 'q14a', family: 'ooas', answer: 0,
    fr: { domain: 'Institutions', text: "Quel organisme de la CEDEAO œuvre à l'harmonisation sanitaire et réglementaire ouest-africaine ?", options: ["L'OOAS (Organisation Ouest-Africaine de la Santé)", "L'OMS Afrique", "L'ARSO", "La BCEAO"], explain: "L'OOAS (WAHO en anglais), institution santé de la CEDEAO, pilote notamment les chantiers d'harmonisation réglementaire au-delà de la seule UEMOA.", source: 'CEDEAO / OOAS' },
    en: { domain: 'Institutions', text: 'Which ECOWAS body works on West African health and regulatory harmonisation?', options: ['WAHO (West African Health Organisation)', 'WHO Africa', 'ARSO', 'BCEAO'], explain: "WAHO, ECOWAS's health institution, drives regulatory harmonisation work beyond WAEMU alone.", source: 'ECOWAS / WAHO' } },

  /* ── F15 · Emballages ── */
  { id: 'q15a', family: 'emballages', answer: 2,
    fr: { domain: 'Conditionnement', text: "L'emballage primaire d'un médicament est celui qui…", options: ['Porte la notice', 'Regroupe plusieurs boîtes pour le transport', 'Est en contact direct avec le médicament (blister, flacon…)', 'Est destiné à la publicité en pharmacie'], explain: "Primaire = contact direct avec le produit (blister, flacon, ampoule) ; secondaire = l'étui qui l'entoure. Les deux doivent être en français dans l'espace UEMOA.", source: 'Définitions du conditionnement pharmaceutique' },
    en: { domain: 'Packaging', text: "A medicine's primary packaging is the one that…", options: ['Carries the leaflet', 'Groups several boxes for transport', 'Is in direct contact with the medicine (blister, bottle…)', 'Is used for pharmacy advertising'], explain: 'Primary = direct contact with the product (blister, bottle, ampoule); secondary = the carton around it. Both must be in French in the WAEMU area.', source: 'Pharmaceutical packaging definitions' } },
  { id: 'q15b', family: 'emballages', answer: 1,
    fr: { domain: 'Conditionnement', text: "L'étui en carton d'un médicament est un emballage…", options: ['Primaire', 'Secondaire', 'Tertiaire', 'Facultatif'], explain: "L'étui carton est l'emballage secondaire — il protège l'emballage primaire (blister, flacon) et porte les mentions réglementaires.", source: 'Définitions du conditionnement pharmaceutique' },
    en: { domain: 'Packaging', text: "A medicine's carton box is which kind of packaging?", options: ['Primary', 'Secondary', 'Tertiary', 'Optional'], explain: 'The carton is the secondary packaging — it protects the primary packaging (blister, bottle) and carries the regulatory particulars.', source: 'Pharmaceutical packaging definitions' } },

  /* ── F16 · RCP ── */
  { id: 'q16a', family: 'rcp', answer: 1,
    fr: { domain: 'Documents produit', text: "À qui s'adresse en premier lieu le RCP ?", options: ['Au patient', 'Aux professionnels de santé', 'Aux douanes', 'Aux distributeurs'], explain: 'Le Résumé des Caractéristiques du Produit est la référence des professionnels de santé ; la notice en est la traduction pour le patient.', source: 'Définitions réglementaires' },
    en: { domain: 'Product documents', text: 'Who is the SmPC primarily written for?', options: ['The patient', 'Healthcare professionals', 'Customs officers', 'Distributors'], explain: 'The Summary of Product Characteristics is the healthcare professional’s reference; the leaflet is its patient-facing counterpart.', source: 'Regulatory definitions' } },
  { id: 'q16b', family: 'rcp', answer: 0,
    fr: { domain: 'Documents produit', text: 'Que signifie RCP ?', options: ['Résumé des Caractéristiques du Produit', 'Rapport de Conformité Pharmaceutique', 'Registre de Contrôle des Produits', 'Résumé Clinique et Pharmaceutique'], explain: 'Le Résumé des Caractéristiques du Produit — SmPC en anglais — décrit indications, posologie, contre-indications et précautions.', source: 'Définitions réglementaires' },
    en: { domain: 'Product documents', text: 'The French acronym « RCP » corresponds to which English document?', options: ['The SmPC (Summary of Product Characteristics)', 'The Pharmaceutical Compliance Report', 'The Product Control Register', 'The Clinical & Pharmaceutical Summary'], explain: 'RCP = Résumé des Caractéristiques du Produit — the SmPC, describing indications, posology, contra-indications and precautions.', source: 'Regulatory definitions' } },

  /* ── F17 · Notice ── */
  { id: 'q17a', family: 'notice', answer: 3,
    fr: { domain: 'Documents produit', text: 'À qui la notice est-elle destinée ?', options: ['Au pharmacien uniquement', "À l'autorité de réglementation", 'Au prescripteur', 'Au patient'], explain: 'La notice traduit le RCP en langage patient : claire, lisible — et en français dans l’espace UEMOA.', source: 'Définitions réglementaires' },
    en: { domain: 'Product documents', text: 'Who is the package leaflet intended for?', options: ['The pharmacist only', 'The regulatory authority', 'The prescriber', 'The patient'], explain: 'The leaflet translates the SmPC into patient language: clear, readable — and in French in the WAEMU area.', source: 'Regulatory definitions' } },

  /* ── F18 · Validité AMM ── */
  { id: 'q18a', family: 'validite', answer: 2,
    fr: { domain: 'Cycle de vie', text: "Quelle est la durée de validité classique d'une AMM dans l'espace UEMOA ?", options: ['2 ans', '3 ans', '5 ans, renouvelable', '10 ans, non renouvelable'], explain: 'Cinq ans renouvelables — et le renouvellement se prépare au moins 6 mois à l’avance.', source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Lifecycle', text: 'What is the typical validity of a Marketing Authorisation in the WAEMU area?', options: ['2 years', '3 years', '5 years, renewable', '10 years, non-renewable'], explain: 'Five years, renewable — and the renewal is prepared at least 6 months ahead.', source: 'Regulation No. 06/2010/CM/UEMOA' } },
  { id: 'q18b', family: 'validite', answer: 1,
    fr: { domain: 'Cycle de vie', text: 'Une AMM est-elle délivrée à vie ?', options: ['Oui, une fois obtenue elle est définitive', 'Non — elle vaut classiquement 5 ans et se renouvelle', 'Oui, sauf pour les génériques', 'Non — elle vaut 1 an'], explain: 'Rien n’est acquis : validité classique de 5 ans, renouvellement à préparer au moins 6 mois avant l’échéance.', source: 'Règlement n° 06/2010/CM/UEMOA' },
    en: { domain: 'Lifecycle', text: 'Is a Marketing Authorisation granted for life?', options: ['Yes, once obtained it is definitive', 'No — it typically lasts 5 years and must be renewed', 'Yes, except for generics', 'No — it lasts 1 year'], explain: 'Nothing is forever: typical validity of 5 years, with renewal prepared at least 6 months before expiry.', source: 'Regulation No. 06/2010/CM/UEMOA' } },
  { id: 'q18c', family: 'validite', answer: 0,
    fr: { domain: 'Cycle de vie', text: "Que se passe-t-il si une AMM expire sans avoir été renouvelée ?", options: ['Le produit ne peut plus être commercialisé légalement', 'Rien, la vente continue', "Le produit passe automatiquement en vente libre", "L'autorité renouvelle d'office"], explain: 'AMM expirée = produit hors la loi sur le marché. D’où l’importance du rétroplanning de renouvellement à 6 mois minimum.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Lifecycle', text: 'What happens if an MA expires without being renewed?', options: ['The product can no longer be legally marketed', 'Nothing, sales continue', 'The product automatically becomes OTC', 'The authority renews it by default'], explain: 'Expired MA = product outside the law. Hence the 6-months-minimum renewal countdown.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F19 · DCI ── */
  { id: 'q19a', family: 'dci', answer: 1,
    fr: { domain: 'Fondamentaux', text: 'Que signifie DCI ?', options: ['Dénomination Commerciale Internationale', 'Dénomination Commune Internationale', 'Description Chimique Internationale', 'Dossier de Conformité International'], explain: "La Dénomination Commune Internationale, attribuée par l'OMS : le nom scientifique universel du principe actif (ex. paracétamol), distinct du nom commercial.", source: 'Programme DCI (OMS)' },
    en: { domain: 'Fundamentals', text: 'What does INN stand for?', options: ['International Nomenclature Number', 'International Nonproprietary Name', 'International Norm Notation', 'Internal Naming Notice'], explain: 'The International Nonproprietary Name, assigned by WHO: the universal scientific name of the active substance (e.g. paracetamol), distinct from the trade name.', source: 'WHO INN programme' } },
  { id: 'q19b', family: 'dci', answer: 2,
    fr: { domain: 'Fondamentaux', text: '« Paracétamol » est un exemple de…', options: ['Nom commercial', 'Marque déposée', 'DCI (dénomination commune internationale)', "Nom de code d'essai clinique"], explain: 'Paracétamol est la DCI ; Doliprane ou Efferalgan sont des noms commerciaux. Les étiquetages de la région exigent la DCI en bonne place.', source: 'Programme DCI (OMS)' },
    en: { domain: 'Fundamentals', text: '“Paracetamol” is an example of…', options: ['A trade name', 'A registered trademark', 'An INN (international nonproprietary name)', 'A clinical trial code name'], explain: 'Paracetamol is the INN; Doliprane or Panadol are trade names. Regional labelling requires the INN to feature prominently.', source: 'WHO INN programme' } },

  /* ── F20 · Titulaire & dépôt ── */
  { id: 'q20a', family: 'titulaire', answer: 1,
    fr: { domain: 'Fondamentaux', text: "Qui peut déposer une demande d'AMM auprès d'une autorité de l'espace UEMOA ?", options: ["N'importe quel grossiste", 'Le laboratoire titulaire ou son représentant local mandaté', 'Uniquement un cabinet d’avocats', "L'importateur, sans mandat"], explain: 'Le titulaire (le laboratoire) dépose — souvent via un représentant local dûment mandaté, exigé par plusieurs autorités de la région.', source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Fundamentals', text: 'Who can file an MA application with a WAEMU-area authority?', options: ['Any wholesaler', 'The applicant company or its duly mandated local representative', 'Only a law firm', 'The importer, without a mandate'], explain: 'The applicant (the company) files — often via a duly mandated local representative, required by several authorities in the region.', source: 'Practice of WAEMU-area authorities' } },
  { id: 'q20b', family: 'titulaire', answer: 3,
    fr: { domain: 'Fondamentaux', text: "Le titulaire d'une AMM est…", options: ['Le pharmacien d’officine', "L'autorité qui l'a délivrée", 'Le grossiste-répartiteur', "L'entité juridique responsable du produit sur le marché"], explain: 'Le titulaire porte la responsabilité réglementaire du produit : variations, renouvellements, pharmacovigilance, qualité.', source: 'Définitions réglementaires' },
    en: { domain: 'Fundamentals', text: 'The holder of a Marketing Authorisation is…', options: ['The community pharmacist', 'The authority that issued it', 'The wholesaler', 'The legal entity responsible for the product on the market'], explain: 'The holder carries the product’s regulatory responsibility: variations, renewals, pharmacovigilance, quality.', source: 'Regulatory definitions' } },

  /* ── F21 · Étiquetage ── */
  { id: 'q21a', family: 'etiquetage', answer: 2,
    fr: { domain: 'Conditionnement', text: "Parmi ces mentions, lesquelles figurent obligatoirement sur l'emballage d'un médicament ?", options: ['Le prix conseillé et le logo du distributeur', "La photo du prescripteur", 'Le numéro de lot et la date de péremption', 'Le chiffre d’affaires du laboratoire'], explain: 'Numéro de lot et date de péremption sont indispensables à la traçabilité et aux rappels — le socle de tout étiquetage pharmaceutique.', source: 'Exigences d’étiquetage pharmaceutique' },
    en: { domain: 'Packaging', text: 'Which of these particulars must appear on a medicine’s packaging?', options: ['Recommended price and distributor logo', "The prescriber's photo", 'Batch number and expiry date', "The company's revenue"], explain: 'Batch number and expiry date are essential for traceability and recalls — the bedrock of pharmaceutical labelling.', source: 'Pharmaceutical labelling requirements' } },

  /* ── F22 · Modèle-vente ── */
  { id: 'q22a', family: 'modelevente', answer: 0,
    fr: { domain: 'Échantillons', text: 'Un échantillon « modèle-vente » est…', options: ['Identique à la présentation qui sera commercialisée', 'Un prototype de laboratoire', 'Une maquette en carton', 'Un lot pilote sans étiquetage'], explain: "Le modèle-vente est l'exemplaire conforme à ce que verra le patient : conditionnement, étiquetage et notice définitifs.", source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'Samples', text: 'A “commercial presentation” sample is…', options: ['Identical to the presentation that will be marketed', 'A laboratory prototype', 'A cardboard mock-up', 'A pilot batch without labelling'], explain: 'The commercial-presentation sample matches what the patient will see: final packaging, labelling and leaflet.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F23 · eCTD ── */
  { id: 'q23a', family: 'ectd', answer: 1,
    fr: { domain: "Dossier d'AMM", text: "La soumission électronique eCTD est-elle exigée partout dans l'espace UEMOA ?", options: ['Oui, depuis 2020', "Non — elle n'est pas encore généralisée, le CTD structuré reste la norme", 'Oui, sauf au Sénégal', 'Non, elle est interdite'], explain: "La transition numérique avance à des rythmes différents selon les autorités : préparez un CTD impeccable, l'eCTD viendra.", source: "Pratiques des autorités de l'espace UEMOA" },
    en: { domain: 'MA dossier', text: 'Is eCTD electronic submission required everywhere in the WAEMU area?', options: ['Yes, since 2020', 'No — it is not yet generalised; a structured CTD remains the norm', 'Yes, except in Senegal', 'No, it is forbidden'], explain: 'Digital transition moves at different speeds across authorities: prepare a flawless CTD, eCTD will come.', source: 'Practice of WAEMU-area authorities' } },

  /* ── F24 · Redevances ── */
  { id: 'q24a', family: 'redevances', answer: 2,
    fr: { domain: 'Redevances', text: "Le dépôt d'une demande d'AMM s'accompagne…", options: ["D'aucun paiement", "D'un pourboire d'usage", 'Du paiement de redevances officielles, fixées par chaque État', "D'un dépôt de garantie remboursable"], explain: 'Chaque État fixe son barème officiel de redevances (textes publiés) — un poste budgétaire à anticiper produit par produit, présentation par présentation.', source: 'Barèmes officiels des États membres' },
    en: { domain: 'Fees', text: 'Filing an MA application involves…', options: ['No payment', 'A customary tip', 'Payment of official fees, set by each state', 'A refundable deposit'], explain: 'Each state publishes its official fee schedule — a budget line to anticipate product by product, presentation by presentation.', source: 'Official fee schedules of member states' } },

  /* ── F25 · Autorité nationale ── */
  { id: 'q25a', family: 'autorite', answer: 1,
    fr: { domain: 'Institutions', text: "Comment appelle-t-on l'institution publique qui évalue les dossiers et délivre les AMM dans un pays ?", options: ["L'ordre des pharmaciens", "L'autorité nationale de réglementation pharmaceutique (ANRP/NMRA)", 'Le ministère du commerce', 'La douane sanitaire'], explain: "Chaque État a son autorité nationale de réglementation (ARP au Sénégal, AIRP en Côte d'Ivoire, ABMed au Bénin…) : votre interlocuteur central.", source: 'Cadres institutionnels nationaux' },
    en: { domain: 'Institutions', text: 'What do you call the public institution that assesses dossiers and issues MAs in a country?', options: ['The pharmacists’ association', 'The national medicines regulatory authority (NMRA)', 'The ministry of trade', 'The health customs office'], explain: "Each state has its national regulatory authority (ARP in Senegal, AIRP in Côte d'Ivoire, ABMed in Benin…): your central counterpart.", source: 'National institutional frameworks' } },
  { id: 'q14b', family: 'ooas', answer: 2,
    fr: { domain: 'Institutions', text: 'Que signifie le sigle OOAS ?', options: ["Office des Organismes d'Afrique Subsaharienne", "Organisation des Autorités Sanitaires", 'Organisation Ouest-Africaine de la Santé', "Observatoire Ouest-Africain des Soins"], explain: "L'Organisation Ouest-Africaine de la Santé (WAHO en anglais), institution spécialisée de la CEDEAO pour la santé publique et l'harmonisation.", source: 'CEDEAO / OOAS' },
    en: { domain: 'Institutions', text: 'What does WAHO stand for?', options: ['World Association of Health Officers', 'West African Harmonisation Office', 'West African Health Organisation', 'Western Authority for Health Oversight'], explain: "The West African Health Organisation, ECOWAS's specialised institution for public health and harmonisation.", source: 'ECOWAS / WAHO' } },
  { id: 'q21b', family: 'etiquetage', answer: 0,
    fr: { domain: 'Conditionnement', text: "La DCI (nom générique) doit-elle figurer sur l'étiquetage aux côtés du nom commercial ?", options: ['Oui, en bonne place', 'Non, le nom commercial suffit', 'Seulement pour les génériques', "Seulement à l'hôpital"], explain: 'La DCI en bonne place est une exigence classique : elle permet au professionnel comme au patient d’identifier la substance active sans ambiguïté.', source: 'Exigences d’étiquetage pharmaceutique' },
    en: { domain: 'Packaging', text: 'Must the INN (generic name) appear on the labelling alongside the trade name?', options: ['Yes, prominently', 'No, the trade name suffices', 'Only for generics', 'Only in hospitals'], explain: 'A prominent INN is a classic requirement: it lets professionals and patients identify the active substance unambiguously.', source: 'Pharmaceutical labelling requirements' } },
  { id: 'q17b', family: 'notice', answer: 3,
    fr: { domain: 'Documents produit', text: 'La notice doit être rédigée dans un langage…', options: ['Technique et scientifique', 'Juridique', 'Réservé aux prescripteurs', 'Clair et compréhensible par le patient'], explain: 'La notice est le document du patient : lisible, claire, sans jargon — et en français dans l’espace UEMOA.', source: 'Définitions réglementaires' },
    en: { domain: 'Product documents', text: 'The package leaflet must be written in language that is…', options: ['Technical and scientific', 'Legal', 'Reserved for prescribers', 'Clear and understandable by the patient'], explain: 'The leaflet is the patient’s document: readable, clear, jargon-free — and in French in the WAEMU area.', source: 'Regulatory definitions' } },
];
